### ISSUE TITLE
Add sound feature

### ISSUE THREAD

**Issue by DoluTattoo** [Mobius1/bulletin#5]
Hey, first of all, I love this resource, great work!
I think it would be cool to add a sound feature like t-notify do.
What do you think?

**Comment by Mobius1** [comment]
You can already set a sound effect by adding an audio file to the `ui/audio` directory and setting the config:

```lua
Config.SoundFile        = 'my_notification_sound.mp3'
Config.SoundVolume      = 0.4
```

**Comment by DoluTattoo** [comment]
Ohh I didn't see that. Awesome, thanks you !
